export const LOGIN_SUCCESS = 'LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const REGISTR_SUCCESS = 'REGISTR_SUCCESS'
export const REGISTR_ERROR = 'REGISTR_ERROR'
